repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: end-of-file-fixer

  - repo: https://github.com/crate-ci/typos
    rev: v1.50.3
    hooks:
      - id: typos

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.30.1
    hooks:
      - id: zizmor

  - repo: local
    hooks:
      - id: black
        name: Format with Black
        entry: uv run black
        language: system
        types: [python]

      - id: ruff
        name: Run ruff lints
        entry: uv run ruff
        language: system
        pass_filenames: false
        types: [python]
        args:
          - "check"
          - "--fix"
          - "taskiq_nats"
          - "tests"

      - id: mypy
        name: Validate types with MyPy
        entry: uv run mypy
        language: system
        pass_filenames: false
        types: [python]
        args:
          - ./taskiq_nats
          - ./tests
