name: Testing taskiq-nats

on:
  pull_request:
    paths-ignore:
      - '*.md'

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - id: setup-uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          enable-cache: true
          cache-suffix: 3.11
          version: "latest"
          python-version: 3.11
      - name: Install deps
        run: uv sync --all-extras
      - name: Run lint check
        run: uv run prek run -a
  pytest:
    strategy:
      matrix:
        py_version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - id: setup-uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          enable-cache: true
          cache-suffix: ${{ matrix.py_version }}
          version: "latest"
          python-version: ${{ matrix.py_version }}
      - name: Install deps
        run: uv sync --all-extras
      - name: Update docker-compose
        uses: KengoTODA/actions-setup-docker-compose@caf887cb5173b7ea66cce3c7db3b1e04974a53d4 # v1.2.8
        with:
          version: "2.16.0"
      - name: docker compose up
        run: docker-compose up -d --wait
      - name: Run pytest check
        run: uv run pytest -vv -n auto --cov="taskiq_nats" .
      - name: Generate report
        run: uv run coverage xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
        if: matrix.py_version == '3.10'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
      - name: Stop containers
        if: always()
        run: docker-compose down
